# Monitor
monitor=,preferred,auto,1

# Terminal
$terminal = kitty

# FileManager
$filemanager = dolphin

# Launcher
$menu = wofi --show drun

# Tecla principal
$mainMod = SUPER

# Atajos básicos
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, D, exec, $menu
bind = $mainMod, E, $filemanager

# Movimiento entre ventanas
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
