enable_wayland true
# Transparencia
background_opacity 0.5
background #000000 

# Desenfoque (si el compositor lo soporta)
background_blur 1

# Colores (oscuro elegante)
background #1e1e2e
foreground #cdd6f4

# Cursor
cursor #89b4fa

# Selección
selection_background #313244
selection_foreground #cdd6f4
